import { notFound } from 'next/navigation';
import { z } from 'zod';
import { requireAdmin } from '@/lib/auth/admin';
import { getAdminSupabase } from '@/lib/supabase/admin';
import { AdminNav,AdminNotice } from '@/components/admin/AdminNav';
import { formatCHF,formatDate,statusLabel } from '@/lib/status';
import { orderAction } from '../../actions';
import type { Order,OrderItem,FulfillmentOrder,Shipment } from '@/types/database';
export default async function OrderPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{status?:string}>}){
  await requireAdmin();const {id}=await params;const {status}=await searchParams;if(!z.uuid().safeParse(id).success)notFound();const db=getAdminSupabase();
  const [order,items,fulfillments,shipments]=await Promise.all([db.from('orders').select('*').eq('id',id).maybeSingle(),db.from('order_items').select('*').eq('order_id',id),db.from('fulfillment_orders').select('*').eq('order_id',id),db.from('shipments').select('*').eq('order_id',id)]);
  if([order,items,fulfillments,shipments].some(r=>r.error))throw new Error('ORDER_UNAVAILABLE');if(!order.data)notFound();const o=order.data as Order;
  return <><AdminNav/><h1>{o.order_number}</h1><AdminNotice status={status}/><p>{formatDate(o.created_at)} · {statusLabel(o.payment_status)} · {statusLabel(o.order_status)}</p><div className="admin-detail"><section className="admin-card"><h2>Lieferadresse</h2><p>{o.first_name} {o.last_name}<br/>{o.shipping_address_line1}<br/>{o.shipping_address_line2}<br/>{o.shipping_postal_code} {o.shipping_city}<br/>{o.shipping_country}</p><p>{o.email}<br/>{o.phone}</p></section><section className="admin-card"><h2>Bestellung</h2>{(items.data as OrderItem[]).map(i=><p key={i.id}>{i.quantity} × {i.product_name} — {formatCHF(i.total_price_cents)}<br/><small>SKU: {i.sku} · Lieferant: {i.supplier_sku||'Nicht zugeordnet'}</small></p>)}<p>Versand: {formatCHF(o.shipping_cents)}</p><strong>Total: {formatCHF(o.total_cents)}</strong></section></div><h2>Fulfillment</h2>{(fulfillments.data as FulfillmentOrder[]).map(f=><div className="admin-card" key={f.id}><p>{f.provider} · {statusLabel(f.status)} · {f.provider_order_id||'Noch nicht übermittelt'}</p><p>Versuche: {f.attempt_count}</p>{f.last_error&&<pre>{f.last_error}</pre>}</div>)}<div className="admin-actions">{o.payment_status==='paid'&&<>{['retry','review',...(process.env.FULFILLMENT_PROVIDER==='mock'?['ship']:[])].map(action=><form key={action} action={orderAction}><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value={action}/><button type="submit">{action==='retry'?'Fulfillment erneut versuchen':action==='review'?'Manuell prüfen':'Versand simulieren'}</button></form>)}</>}</div><h2>Sendungsverfolgung</h2>{(shipments.data as Shipment[]).map(s=><p key={s.id}>{s.carrier} · {s.tracking_number} · {statusLabel(s.status)}</p>)}<p>Rückerstattungen werden über das Stripe-Dashboard ausgelöst und per Webhook übernommen.</p></>;
}
