import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Check,Package,Truck } from 'lucide-react';
import { getAccessibleOrder,safeTrackingUrl } from '@/lib/services/orders';
import { formatCHF,formatDate,statusLabel } from '@/lib/status';
export const metadata:Metadata={title:'Deine Bestellung',robots:{index:false,follow:false},referrer:'no-referrer'};
export default async function OrderStatusPage({params,searchParams}:{params:Promise<{orderNumber:string}>;searchParams:Promise<{token?:string}>}){
  const {orderNumber}=await params;const {token}=await searchParams;if(!token)notFound();const result=await getAccessibleOrder(orderNumber,token);if(!result)notFound();const {order,items,shipments}=result;
  const stage=order.fulfillment_status==='delivered'?4:order.fulfillment_status==='shipped'?3:['processing','submitted'].includes(order.fulfillment_status)?2:order.payment_status==='paid'?1:0;
  return <main id="main-content" className="page-shell prose order-status"><p className="eyebrow">DEIN WAKPU-MOMENT</p><h1>{order.order_number}</h1><p>Bestellt am {formatDate(order.created_at)}</p>{['refunded','cancelled'].includes(order.order_status)?<div className="panel"><h2>{statusLabel(order.order_status)}</h2><p>Bei Fragen hilft dir unser Kundenkontakt weiter.</p></div>:<><h2>{order.payment_status==='paid'?'Deine Bestellung ist bei uns.':'Deine Zahlung wird geprüft.'}</h2><ol className="order-progress">{['Bestellt','Bezahlt','In Bearbeitung','Versendet','Zugestellt'].map((step,index)=><li key={step} className={index<=stage?'done':''}><span>{index<=stage?<Check size={18}/>:index+1}</span>{step}</li>)}</ol>{order.order_status==='manual_review'&&<p>Wir klären gerade die nächsten Schritte für deine Bestellung.</p>}</>}{shipments.map(s=>{const url=safeTrackingUrl(s.tracking_url);return <section className="panel" key={s.id}><Truck size={28}/><h2>Deine Sendung</h2><p>{s.carrier} · {s.tracking_number}</p>{s.carrier.includes('Mock')&&<p>Simulierter Versand für den Testbetrieb.</p>}{url&&<a className="button button-dark" href={url} target="_blank" rel="noopener noreferrer">Sendung verfolgen</a>}</section>;})}<section className="panel"><Package size={25}/><h2>Deine Bestellung</h2>{items.map(i=><p key={i.id}>{i.quantity} × {i.product_name} · {formatCHF(i.total_price_cents)}</p>)}<p>Versand: {formatCHF(order.shipping_cents)}</p><strong>Total: {formatCHF(order.total_cents)}</strong></section><p>Diesen Link bitte vertraulich behandeln. Er ermöglicht den Zugriff auf deinen Bestellstatus.</p><Link href="/kontakt">Fragen zur Bestellung?</Link></main>;
}
