import { requireAdmin } from '@/lib/auth/admin';
import { getAdminSupabase } from '@/lib/supabase/admin';
import { AdminNav,AdminNotice } from '@/components/admin/AdminNav';
import { saveProduct } from '../actions';
import type { Product,ProductVariant } from '@/types/database';
export default async function ProductsPage({searchParams}:{searchParams:Promise<{status?:string}>}){
  await requireAdmin();const {status}=await searchParams;const {data,error}=await getAdminSupabase().from('products').select('*,variants:product_variants(*)').order('display_order');if(error)throw new Error('PRODUCTS_UNAVAILABLE');
  return <><AdminNav/><p className="eyebrow">{data.length} PRODUKTE</p><h1>Deine Produkte.</h1><AdminNotice status={status}/><p className="admin-lead">Preise in Rappen: 100 Rappen entsprechen CHF 1.00. Änderungen gelten für neue Bestellungen.</p>{(data as (Product&{variants:ProductVariant[]})[]).map(p=><section className="admin-card" key={p.id}><h2>{p.name}</h2>{p.variants.map((v,index)=><form key={v.id} action={saveProduct} className="admin-form">{index>0&&<hr className="admin-form-divider"/>}<input type="hidden" name="id" value={p.id}/><input type="hidden" name="variant_id" value={v.id}/><label>Name<input name="name" defaultValue={p.name} required maxLength={120}/></label><label>Kurzbeschreibung<input name="short_description" defaultValue={p.short_description} maxLength={300}/></label><label>Beschreibung<textarea name="description" defaultValue={p.description} maxLength={5000}/></label><div className="admin-form-row"><label>Preis in Rappen<input name="price_chf_cents" type="number" min={1} max={1000000} step={1} defaultValue={v.price_chf_cents} required/></label><label>SKU<input name="sku" defaultValue={v.sku} required/></label></div><div className="admin-form-row"><label>Lieferanten-SKU<input name="supplier_sku" defaultValue={v.supplier_sku||''}/></label><label>Verfügbarkeit<select name="stock_mode" defaultValue={v.stock_mode}><option value="available">Verfügbar</option><option value="preorder">Vorbestellung</option><option value="out_of_stock">Ausverkauft</option></select></label></div><label className="check-label"><input type="checkbox" name="active" defaultChecked={p.active}/>Produkt aktiv</label><label className="check-label"><input type="checkbox" name="featured" defaultChecked={p.featured}/>Empfohlenes Angebot</label><button type="submit">Produkt speichern</button></form>)}</section>)}</>;
}
